### ISSUE TITLE
Add/List Host

### ISSUE THREAD

**Issue by atla5** [OpenBrews/OpenBrews#29]
If this is already running somewhere, you should post a link to where.

If it's not, you should set up an auto-deploy watching for pushes to the master branch with [heroku](https://dashboard.heroku.com/login).

**Comment by MichaelWashburnJr** [comment]
It's not really targeted for the browser. To best emulate devices I would have to run it with `ionic serve --lab`, which is just for development and really shouldn't be used by multiple people. I'm not sure what the best way to deploy this would be since to get a real production environment you would have to deploy to Android/iOS

**Comment by icyflame** [comment]
@atla5 This is an offline-first app with no server storage / syncing. This means that all the data will be stored locally on your device.

For using the app, clone this repository, run `npm install && bower install && gulp`. After this, you can either use `ionic upload` and the [Ionic View](http://view.ionic.io/) application to sync this application to your phone.
