### ISSUE TITLE
Save Recipe button no longer working when testing in Ionic View

### ISSUE THREAD

**Issue by MichaelWashburnJr** [OpenBrews/OpenBrews#49]
If you download the Ionic View app on your phone, and upload OpenBrews using `ionic upload`, then the Save Recipe button doesn't do anything. It does work in a regular browser, however.

**Comment by icyflame** [comment]
@mdw7326 I have still not been able to figure out why this problem is happening. Any clues as to the reasons? (API changes?) I will use `git bisect` today to figure out the offending commit! :smile:

**Comment by icyflame** [comment]
Okay, `git bisect` tells me that https://github.com/OpenBrews/OpenBrews/commit/530943b19a1cbfceb4283639da18347b3870791a is the offending commit. I did a bisect between 011a044 and https://github.com/OpenBrews/OpenBrews/commit/75eb79fb490e9cc0433bdd85356fba24ac53d581. Will look into what havoc this commit is causing! (cc @rmnblm )

**Comment by icyflame** [comment]
@mdw7326 No clue why git bisect told me about that commit. The actual problem started when we wrote that `config.json` line. Since the error is not being handled, it was a problem. For now, I have commented that out. But I think we can add a block of code to handle any errors (like 404) which might arise, which will allow us to keep that code segment there without creating any problem for the rest of the application.

Sorry @rmnblm, this was not a bug caused by any code that you added. :slightly_smiling_face:
